### ISSUE TITLE
Otimizar o sistema de adicionar cargos aos membros.

### ISSUE THREAD

**Issue by katho162** [Liga-dos-Programadores/Project-A#10]
Criar um sistema administrativo para melhorar o sistema dos comandos addlang e remlang aonde um administrador deve registrar um cargo contendo, o nome e o nome do cargo no servidor parar que assim o comando possa pegar essas informações atraves de um arquivo de configuração do proprio bot evitando o algoritimo não escalavel do comando.

**Comment by BeeCodingOfc** [comment]
Adicionado em #12
