### ISSUE TITLE
Adicionar sistema de role por reação

### ISSUE THREAD

**Issue by beescuit** [Liga-dos-Programadores/Project-A#28]

**Comment by Katho162** [comment]
Existe um bot que é open-source se eu não me engano que já implementa isso.

**Comment by Katho162** [comment]
Talvez você possa olhar e reaproveitar o código e depois colocar os créditos é claro.

**Comment by dpaiv0** [comment]
@Katho162 sim, é o Zira. ele ainda existe e pá, mas não tá sendo mantido
