### ISSUE TITLE
Eventos não funcionam

### ISSUE THREAD

**Issue by FoXZillaPT17** [Liga-dos-Programadores/Project-A#63]
Boas,
Eu configurei os ids dos GREETCHANNEL, JOINCHANNEL, LEAVECHANNEL, porém o bot, toda a vez que entra uma pessoa no meu servidor ou sai, o bot não envia nenhuma mensagem.
Já verifiquei tudo, na consola não da qualquer erro, o bot esta dentro do servidor, porém nao envia qualquer embeded para as channels de welcome ou leave

**Comment by joaolucasete** [comment]
Para o bot receber os eventos você deve entrar na sua aplicação no discord development ( lugar onde pegou o token ) e ativar essas duas opções apresentadas no print abaixo.
![image](https://user-images.githubusercontent.com/52172985/106398579-5c7f1580-63f2-11eb-8710-365dcd671365.png)

**Comment by FoXZillaPT17** [comment]
OK, amanhã de manhã vou tentar, obrigado
👌👍

**Comment by FoXZillaPT17** [comment]
Era mesmo isso, obrigado
@joaolucasete
